@Host_Address = http://localhost:5033

###

GET {{Host_Address}}/api/public/dashboard
Content-Type: application/json


###

GET {{Host_Address}}/api/admin/dashboard
Cookie: .AspNetCore.Identity.Application=CfDJ8FSNPT-2TENDt06X1G8-DV-soMnoabg1MIl2usTvO6FmmSofOFf4Jfs-u2mG_P-36INtgULyOuowS_Uyq1eE2hKxqDKu-ohbax2CGBA0zSfB4KnGCtY17BtHWIH4cYMVXzAJUomMgmgV6R5KbMV8I4LTdPKeOv4xnsIFBXBVm-2ymyre6Ty_Dfa9mjVo6EMN5wkgMkx23P9mEWlNXV4vrpJtrsCScaXXbT5JeJ_dRUvolhReJ-Tc_V8lfazSCq66I7fiz8z-zUNWOKpjB347Y0qeArnYNd2BhHy1K3f-62J_9viQ2kKtXaVnsp73KgiVK_OLfqvHrdl6VcZ5jXad0BkG-KqpHdglMcAfM-gARvapIOPhanho4a8UcwqJCmhMJteJpUtjYtoz17hDfQ5_M_MUXfiQsfyVNlwfFrqLbLWezFWohB1uqvdmL5ay6V0FKzlAnrIKpR2lccwlUN7U93O8ZjGja7Oywpy36JtOB_z7chXpxhpKCBf1YKB_wLZRyQLYbxzPHCMZn4-X08nDttRLUAV4W8S6tPfwAb64oyXRG-6v4Rv5cZUNUUyHOcHWP1Az7o4b8Zis660YpQAI8iV5RbmPeygvPOIeR_FtsIeXDknLHQvSw45OG04lbGSJ6FQOdU2JqozlSY8CSKv8KYDt4XR9uGqX-2t1G7hbyQyKWzWEfkI5D_BnPgUXxuBPNM2_oBihSAAUMY-XyjDjUVwfMTHx6zzklUMXqLaQO29SZHsDfPBsuW2zwCUzTT5Q1dP_AgeP5yTHoUxY9iHDm9UB6O-sEnrLup3WzydrydLxMg7v3aEKPGRabWsTbrM8O1QxesTyQQYZwEsu77rSqUxXGQRVHeLGWxavgZao-zNGFJEsvNyLWa-jiE7jIcxVu5PnMEa1IyPwAiVwqDPnldo; path=/; samesite=lax; httponly



###

GET {{Host_Address}}/api/doctor/dashboard

###

GET {{Host_Address}}/api/patient/dashboard

###
GET {{Host_Address}}/api/user/dashboard


###
POST {{Host_Address}}/api/create-role
Accept: application/json
Content-Type: application/json

{
    "roleName": "Admin"
}


###

POST {{Host_Address}}/api/register
Accept: application/json
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "Password123!",
    "confirmPassword": "Password123!"
}


###

POST {{Host_Address}}/api/assign-role
Accept: application/json
Content-Type: application/json

{
    "email": "admin@example.com",
    "role": "Admin"
}


###

POST {{Host_Address}}/api/add-claim
Accept: application/json
Content-Type: application/json

{
    "email": "admin@example.com",
    "claimName": "type",
    "claimValue":"doctor"
}


###

POST {{Host_Address}}/api/add-claim-to-role
Accept: application/json
Content-Type: application/json

{
    "roleName": "Admin",
    "claimName": "type",
    "claimValue":"manage-employee"
}

###
POST {{Host_Address}}/api/login
Accept: application/json
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "Password123!"
}


###
POST {{Host_Address}}/api/logout
Accept: application/json
Content-Type: application/json


###
GET {{Host_Address}}/api/admin-only
Accept: application/json



// Employee Section



###
POST {{Host_Address}}/api/employee/create
Accept: application/json
Content-Type: application/json
Cookie: .AspNetCore.Identity.Application=CfDJ8FSNPT-2TENDt06X1G8-DV-NX8HGQ6BFGcKyUFRX0j1cT_PN7CoQ9c6LSEm_4HGlsTWgrcm-gw5iJ55lvaNIPiYAKCF0A-n3XHYjFhIhJ4ax4yKUvmxAWWMkaSfd87s1Y0li7AJ-t42Ns1EoQG3JRs0WwEv4cASv3p4JKOnF9nSHZYjdQK6oxPP1_Mi8lvlW2G_cjwptFGFNEyx49tbVUk1hixtuXopiw-IMB8ZLeJ2SNdlTlnDiqLVSaK_LsDkrOaPKWSq-O7sDlnoondKzcbjED1AmmKnV2Z3cOfArAtxh388L51Axj2irSK8vTujO-wfeCgdY9tmQWOuXaRUCxzhUurdqBC4MGi77jt2NQjGxiLOc4U-uuMM7f-U_QSritDrk059S56-y9QlarMZ_inV4b1ypEaLEA5-bLkQSnJXJHpSAJ9BXa9jEZRgPoLcgu-m7QeSaNgB6D-EYTBguF-wL8kCtk3tMG6U1J9EluqqAsGzw1Re1Qj6pdhvDB8Y1btxCiLeBW3kmCfdrf2d5ILwvVDkB7e_GlDGa2uOx5miJ3WUY0_6TC-SfourN16m2DhVQ1uC2ZOc8_TIvoOiL54iKhcezv6Cs3AbFaH1N9tfGCk3fNlUYCq2ZPXq2aNJypYEZqR8OsG5UN-tC_6IfkOX_ujjyQXnwvshbfb46Pjs7B9CJ1Hw56ZvJtrgQPeKHE_dW9pgMaQKVgmY-Fu9_wn9elZ5U6iPALFVm-JfbgXmHwPSRLRP9ZZF2Pn4fSVJb6rQgYx_H-RIdn3SE92iMSzkT1w9zrz2JvbIouk7jI1Pkym0hnTcXNqCB4Ycqtd6LHfHdrGmKiC-r-SA0Ah30Z_U; path=/; samesite=lax; httponly

{}

###
PUT {{Host_Address}}/api/employee/update
Accept: application/json
Content-Type: application/json
Cookie: 

{}

###
DELETE {{Host_Address}}/api/employee/delete
Accept: application/json
Content-Type: application/json
Cookie: 


###
GET {{Host_Address}}/api/employee/get
Accept: application/json

